### ISSUE TITLE
How to use array json for Network.setCookies 

### ISSUE THREAD

**Issue by zjlx** [ysmood/rod#10]
Thanks for your program. It's very easy to use.
 Now I don't know how to pass cookies in array JSON format to page.call. `page.Call("Network.setCookies",cdp.Array{})`
```javascript
arrayJson=`[
    {
        "domain": ".test.com",
        "expirationDate": 158255720,
        "hostOnly": true,
        "httpOnly": true,
        "name": "datr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "5798798Q2B-",
        "id": 1
    },
    {
        "domain": ".test.com",
        "expirationDate": 15985720,
        "hostOnly": true,
        "httpOnly": true,
        "name": "bs",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "8DfXXcNRyf9zIM57nG4Maa1c",
        "id": 2
    }
]`
```

**Comment by ysmood** [comment]
Is this example not enough?

https://github.com/ysmood/rod/blob/28ef6b769af4a9729473e7f7ef1942fbd05b96ea/examples_test.go#L163

**Comment by ysmood** [comment]
If you check the doc of https://chromedevtools.github.io/devtools-protocol/tot/Network#method-setCookie

There's another method below `Network.setCookie` called `Network.setCookies`. you can do something like this:

```go
page.Call("Network.setCookies", []cdp.Object{{
		"domain":         ".test.com",
		"expirationDate": 158255720,
		"hostOnly":       true,
		"httpOnly":       true,
		"name":           "datr",
		"path":           "/",
		"sameSite":       "no_restriction",
		"secure":         false,
		"session":        false,
		"storeId":        "0",
		"value":          "5798798Q2B-",
		"id":             1,
	}, {
		"domain":         ".test.com",
		"expirationDate": 15985720,
		"hostOnly":       true,
		"httpOnly":       true,
		"name":           "bs",
		"path":           "/",
		"sameSite":       "no_restriction",
		"secure":         false,
		"session":        false,
		"storeId":        "0",
		"value":          "8DfXXcNRyf9zIM57nG4Maa1c",
		"id":             2,
	}})
```

**Comment by ysmood** [comment]
One more thing you need to be careful. Your data structure seems copied from a python lib which is not compatible with the chrome protocol, you need to modify some fields' name and value to match the format: https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCookie

**Comment by ysmood** [comment]
BTW, I added a new method to version `v0.26.1` to make it easier:

https://github.com/ysmood/rod/blob/7d21be234a77a3b371be42e88e0cf934f5e7decf/page_test.go#L26

**Comment by zjlx** [comment]
Thanks for your relay.
The cookies is export from chrome plugin "Edit This Cookie".
The new method `page.SetCookies(cdp.Object{})` it means can only setcookie not setcookies, or it can be pass in []cdb.Object{}?

**Comment by ysmood** [comment]
`page.SetCookies` can receive array, you'd better learn the golang syntax `...`.

**Comment by ysmood** [comment]
check this: https://gobyexample.com/variadic-functions

**Comment by zjlx** [comment]
So sorry about that ,I will learn more basic knowledge.
By the way, can the name of the library be longer? It's related to chrome or some keyword related libraries. Now, searching for the same name of rod is not conducive to being understood by more people.Just a suggestion.

**Comment by ysmood** [comment]
The name rod is actually related to puppetry:

<img width="573" alt="Screen Shot 2020-04-24 at 14 43 43" src="https://user-images.githubusercontent.com/1415488/80178856-31cd8880-863a-11ea-83e9-64f84be3282d.png">

I think it's a common issue for new projects. Once it's popular search for `go rod` will definitely get you here, it's just some search engine trick. So if you like it, you can help to share it with more people, such as create a tutorial when you are learning to use it, etc.

Here my ongoing tutorial for it, I think it will help a lot of people step into the scraper world after it's finished: https://github.com/ysmood/github-trending

**Comment by zjlx** [comment]
It is so cute.
I just learned golang.
I will recommend this library to more people.

**Comment by ysmood** [comment]
Thank you! I think I can close this ticket for now.
