### ISSUE TITLE
How get a text of element

### ISSUE THREAD

**Issue by alufrew** [ysmood/rod#11]
I am trying to get text of element via: page.Element(selector).Text(). It returns empty string in my case.
If in browser I use document.getElementById("receipt-result").textContent I will get full text of element. 
What method should I use in this case to get similar result?

**Comment by ysmood** [comment]
I recently fixed a bug of the `Element.Text` function, are you using the latest version of rod?

**Comment by ysmood** [comment]
A temp solution can be something like this `page.Element(sel).Eval("() => this.textContent")`

**Comment by ysmood** [comment]
Both work fine for me. Can you give me more info so that I can't reproduce your issue?

**Comment by alufrew** [comment]
Hi. Sorry for the long answer. Couldn't check it till now. It seems I was using 0.25.7 version of framework. 
After update to 0.26.1 all works fine.
