### ISSUE TITLE
How can I upload a file to a Element

### ISSUE THREAD

**Issue by zjlx** [ysmood/rod#17]
Content of your question.
I see the download example. How can I upload the file?

**Comment by ysmood** [comment]
How about the example code in the unit tests [here](https://github.com/ysmood/rod/blob/119b194d4268276e46349321d7b88a7d723b84df/element_test.go#L108)?

It's called `SetFiles`.

**Comment by ysmood** [comment]
For example this website: https://www.dropzonejs.com/

You may code like this:

```go
page.Element('[type=file]').SetFiles("a.jpg")
```

The upload should happen automatically.

**Comment by zjlx** [comment]
It is cool.
Thank you @ysmood .
