### ISSUE TITLE
page.Call('Page.addScriptToEvaluateOnNewDocument',param) is not working

### ISSUE THREAD

**Issue by simpleMemory** [ysmood/rod#2]
I want call addScriptToEvaluateOnNewDocument method when i open a new page,But it not working,
`out := page.Call("Page.addScriptToEvaluateOnNewDocument", cdp.Object{ 

"source" :     
"window.navigator.chrome = window.chrome = {...window.chrome, runtime: {},};",
})`

how can i do it like puppeteer 

`
const page = await browser.newPage()

await page.evaluateOnNewDocument(
"window.navigator.chrome = window.chrome = {...window.chrome, runtime: {},};"
);
`

**Comment by ysmood** [comment]
@simpleMemory I tried to run:

```js
const puppeteer = require('puppeteer'); // version is 2.0.0-post
(async () => {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();
    await page.evaluateOnNewDocument(
        "console.log(10)"
    );
})();
```

It doesn't log anything, you sure it's working on puppeteer?

**Comment by ysmood** [comment]
@simpleMemory to use `Page.addScriptToEvaluateOnNewDocument`

You have to call `Page.enable` first, there's no mention about it on chrome api doc site.

```go
page.Call("Page.enable", nil)
page.Call("Page.addScriptToEvaluateOnNewDocument", cdp.Object{
    "source" : "window.navigator.chrome = window.chrome = {...window.chrome, runtime: {},};",
})
```

**Comment by ysmood** [comment]
@simpleMemory after consideration, I think it's better to make it enabled by default, check the new version 95a1b1622a518fcbab0c945836847303640e9800

**Comment by simpleMemory** [comment]
Thanks
