### ISSUE TITLE
Show only iFrame

### ISSUE THREAD

**Issue by dying** [ysmood/rod#20]
Good morning, sir,

I would like to make a system that allows the user to solve ReCaptcha himself. I've already taken the iFrame, but I'd like to know if it's possible to display only that (e.g. embed it in an electron app, or just display the captcha alone).

Here is my current code:

```go
frame01 := page.Timeout(3 * time.Minute).ElementX("/html/body/div[3]/div[2]/iframe").Frame()
// Doesn't work
frame01.WindowFullscreen()
```

Thanks for your help!

**Comment by ysmood** [comment]
Yes, you can, like this:

```go
frame01 := page.Timeout(3 * time.Minute).ElementX("/html/body/div[3]/div[2]/iframe").Frame()
// frame is just a Page, you have all the functions that Page has
frame01.ElementX("/xpath/to/captcha.jpg").Screenshot()
```

**Comment by dying** [comment]
> Yes, you can, like this:
> 
> ```go
> frame01 := page.Timeout(3 * time.Minute).ElementX("/html/body/div[3]/div[2]/iframe").Frame()
> 
> // frame is just a Page, you have all the functions that Page has
> frame01.ElementX("/xpath/to/captcha.jpg").Screenshot()
> ```

Thanks for the answer, but it doesn't looks like something that I want. I want it to be interactive, so the user can PRESS on the button himself, like this: 

https://cutie.wtf/s9ryT9MX.mp4

Where it shows only the captcha for the user. Or maybe they are taking the whole iFrame, and showing in on a seperated page?

**Comment by ysmood** [comment]
So you want Rod to pause at the captcha input step, and let the user finish the captcha manually?

If that's true, then this ticket won't be a Rod related question anymore.

**Comment by dying** [comment]
> So you want Rod to pause at the captcha input step, and let the user finish the captcha manually?
> 
> If that's true, then this ticket won't be a Rod related question anymore.
Yes.

**Comment by ysmood** [comment]
Then it's a product design problem. If I were you I will:

1. launch the login window `page := browser.Page("http://login.com")`
2. change the size of the window with `page.Window(0,0, width_only_for_captcha, height_only_for_captcha)`
3. scroll to the captcha `el := page.Element("/xpath/to/captcha").ScrollIntoView()` to
4. wait for the user to finish the captcha `el.WaitInvisible()`

I hope it helps.

**Comment by ysmood** [comment]
I think I can close it for now. If you still want to discuss please come to the [chat room](https://gitter.im/ysmood-rod/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link)
