### ISSUE TITLE
Clarify how WaitRequestIdle() should be used. 

### ISSUE THREAD

**Issue by alufrew** [ysmood/rod#23]
Rod v0.28.0 used. 
Hi I am trying to use WaitRequestIdle in following way:

```go
package main

import (
	"fmt"
	"time"

	"github.com/ysmood/rod"
	"github.com/ysmood/rod/lib/launcher"
)

func main() {
	url := launcher.New().
		Headless(false).
		Launch()

	b := rod.New().ControlURL(url).Connect().Timeout(30 * time.Second)
	defer b.Close()

	page := b.Page("https://google.com")
	w := page.WaitRequestIdle()

	page.Navigate("https://wikipedia.org")
	fmt.Println(time.Now())
	w()
	fmt.Println(time.Now())

	page.Navigate("https://gmail.com")
	fmt.Println(time.Now())
	w()
	fmt.Println(time.Now())
}
```

It seems w() really waits only after first navigation attempt but not on second. If I create second instance before second attempt it will wait twice. But I am not sure that this is intended behaviour.
Am I using it correctly?

**Comment by ysmood** [comment]
The wait is only for the next request. If you have another request you have to create another wait:

```go
package main

import (
	"fmt"
	"time"

	"github.com/ysmood/rod"
	"github.com/ysmood/rod/lib/launcher"
)

func main() {
	url := launcher.New().
		Headless(false).
		Launch()

	b := rod.New().ControlURL(url).Connect().Timeout(30 * time.Second)
	defer b.Close()

	page := b.Page("https://google.com")
	w := page.WaitRequestIdle()

	page.Navigate("https://wikipedia.org")
	fmt.Println(time.Now())
	w()
	fmt.Println(time.Now())

	w := page.WaitRequestIdle()  // look at this line!

	page.Navigate("https://gmail.com")
	fmt.Println(time.Now())
	w()
	fmt.Println(time.Now())
}
```

**Comment by ysmood** [comment]
If you want more options, you can use `WaitRequestIdleE` other than the high-level version `WaitRequestIdle`

**Comment by ysmood** [comment]
BTW, for page load events it's better to use `page.WaiteLoad()`, `WaitRequestIdle` is designed for ajax requests when you click some button on the page.

**Comment by ysmood** [comment]
Normally you don't need to use `WaitRequestIdle` or `WaitLoad` at all, you can directly use the selector `page.Element`, it will automatically retry until it finds the element.

**Comment by alufrew** [comment]
Oh. Thanks. I misunderstood how it should work. 

I really need WaitRequestIdle. In my case all elements can be already on page but background requests are still running. If I f.e. click on element before requests stop sometimes I receive unexpected behaviour. So after clicking on some element I want to wait while requests are finished before clicking next.

May I propose to slightly change doc string for WaitRequestIdle to empathize that function returned will only be used for one next request?

**Comment by ysmood** [comment]
Agree, if you can make a PR to fix the doc, I'll be more than happy to merge!

**Comment by alufrew** [comment]
Ok. I will do it slightly later. Leaving issue opened till then.

**Comment by alufrew** [comment]
I see you already closed issue. Sorry that you had to do it yourself. Was away for a while. Won't happen next time.

**Comment by ysmood** [comment]
Never mind. Looking forward to your idea and contribution 😃
