### ISSUE TITLE
Why are overlay functions in JS lib rather than using DevTools commands? 

### ISSUE THREAD

**Issue by cris691** [ysmood/rod#25]
For example, the overlay domain

https://chromedevtools.github.io/devtools-protocol/tot/Overlay/

or the legacy methods it replaces, like

https://chromedevtools.github.io/devtools-protocol/1-3/DOM/#method-highlightRect

**Comment by ysmood** [comment]
Because it can't set a custom styled message title. And the style of the overlay can't be controled. You even can't add a border to it. You have to use a color to cover the object which is usually very disturbing, such as when you want to show a message that the page is navigating.

**Comment by cris691** [comment]
Cool. Interesting to know. Thanks!
