### ISSUE TITLE
How should I use proxy with username and password

### ISSUE THREAD

**Issue by zjlx** [ysmood/rod#26]
I checked that chrome doesn't support Socks5 proxy with auth,  but I use http proxy it is still not working.
```
proxyString:="http://username:password@ip:port"
Set("proxy-server", proxyString) 
```
If I remove username and pasword, the page show a alert to input username and password,is there any simple method to use proxy with auth.

**Comment by ysmood** [comment]
```go
launcher.New().Set("proxy-server", "socks5://proxyhost:8000")
```

**Comment by zjlx** [comment]
I try it :
`page.Call("Network.setExtraHTTPHeaders", cdp.Object{
		"Proxy-Authorization": "Basic dXNlcjpwYXNzd29yZA==",
	})`
the error is `panic: {"code":-32602,"message":"Invalid parameters","data":"headers: object expected"}`
Is the parameter format incorrect?

**Comment by ysmood** [comment]
You missed the `headers`, check the doc carefully 😂 , it's like `Call({ headers: { a: b } })`, not Call({ a: b })

**Comment by ysmood** [comment]
BTW, I added `page.SetExtraHeaders` in version `v0.29.1`, you can use that directly:

This is the example code:

https://github.com/ysmood/rod/blob/f397ccbb88efc50352fc97574d71b0d3655a8755/page_test.go#L57

**Comment by ysmood** [comment]
The new version of Rod will type-safe when you send low-level requests to chrome. This kind of issue won't happen again, check the example:

https://github.com/ysmood/rod/blob/3ff68f7d645f24c0978878939164f01bd39d88a2/examples_test.go#L175

**Comment by zjlx** [comment]
I use `page.SetExtraHeaders("Proxy-Authorization", "Basic "+temp)` but it not work , is it rigth?
key/value use comma separated?
Can you change it to
`var dict map[string]string = map[string]string{"Proxy-Authorization":"Basic "+temp}
page.SetExtraHeaders(dict)`
And v0.29.1 can't use Call and Cdp.Object anymore?

**Comment by ysmood** [comment]
Check my previous comment, it's type-safe now, that's the new way to use the low-level API, cdp.Object is not type-safe.

**Comment by ysmood** [comment]
with `map[string]string` you have to write more code.

`(map[string]string{"a": "b"})`

vs

`("a", "b")`

The later is obviously shorter. When you have multiple pairs, you can do:

```
(
  "key1", "value1",
  "key2", "value2",
)
```

**Comment by ysmood** [comment]
I think your password or username is wrong if you use the value I gave to you.

**Comment by ysmood** [comment]
Thanks for your report. The `v0.30.1` added the `HandleAuth` helper to deal with your problem.

I tested with `mitmproxy --showhost --proxyauth a:b`, it works well.

Here's the example to use it:

https://github.com/ysmood/rod/blob/3ae35ce463f28e3ce8055e6dafda5eb33f39fc53/browser_test.go#L70

**Comment by ysmood** [comment]
@zjlx about the breaking change issue, check this answer: https://github.com/ysmood/rod#q-how-versioning-is-handled

**Comment by zjlx** [comment]
> Thanks for your report. The `v0.30.1` added the `HandleAuth` helper to deal with your problem.
> 
> I tested with `mitmproxy --showhost --proxyauth a:b`, it works well.
> 
> Here's the example to use it:
> 
> https://github.com/ysmood/rod/blob/3ae35ce463f28e3ce8055e6dafda5eb33f39fc53/browser_test.go#L70

Thank you so much for the changes. It is  working well.
