### ISSUE TITLE
Does rod support custom request headers

### ISSUE THREAD

**Issue by zjlx** [ysmood/rod#27]
I saw a Header() function at launcher, but I do't known how to use it.
I want to add a custom request header `x-lpm-country: us` in it. 
May you add a example for it.
Thank you.

**Comment by ysmood** [comment]
Please check the comment for `Header`:

> for launching chrome remotely

Also see this FAQ: https://github.com/ysmood/rod#q-how-to-use-rod-inside-a-docker-container

**Comment by ysmood** [comment]
If you want to override the http request header, please use https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setExtraHTTPHeaders
