### ISSUE TITLE
HandleAuth, alert not closing

### ISSUE THREAD

**Issue by Meromen** [ysmood/rod#28]
Hello, i want to use proxy with auth, but i can't login.
When i add header in chromium with proxy, after i have an alert with username and password for auth, but if i user your method HandleAuth nothing happens, i need to click submit button to auth.
How can i do it with code?

P.S. Sorry for my English)

**Comment by ysmood** [comment]
Sorry, that's too hard to understand what's happening to you. I need more info to understand how to reproduce your issue on my local.

**Comment by Meromen** [comment]
![2020-05-13-163710_1366x768_scrot](https://user-images.githubusercontent.com/32484121/81779419-08689400-9538-11ea-866a-b3b0d0de8565.png)


i need to click button to close the alert and auth, how can i close the alert in headless mode?

**Comment by ysmood** [comment]
Look at my code carefully 😂 , the `HandleAuth` should be set up before the Navigation, your code should be:

```go
browser.HandleAuth("a", "b")
page := browser.Page("https://ifconfig.co")
```

**Comment by Meromen** [comment]
Well........
I'm too stupid, thank you)

**Comment by ysmood** [comment]
BTW, the comment of the HandleAuth is very clear: `HandleAuthE for the next basic HTTP authentication.`

It's the `next` dialog, not the previous, man 😂
