### ISSUE TITLE
Can you add a function to add JS script for all browser's pages/tabs

### ISSUE THREAD

**Issue by zjlx** [ysmood/rod#29]
**Is your feature request related to a problem? Please describe.**
I used this code for fake browser fingerprint ,
`proto.PageEnable{}.Call(page)
proto.PageAddScriptToEvaluateOnNewDocument{
		Source: fingerprint,
	}.Call(page)`
the js code from https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth
I don't known why need `proto.PageEnable` ,but if I don't write it the `proto.PageAddScriptToEvaluateOnNewDocument` not works.
`proto.PageAddScriptToEvaluateOnNewDocument` only works on current page/tab not working on a link click new pages/tabs.

**Describe the solution you'd like**

Can you add a function to add JS script for all browser's pages/tabs something like hook browser's page or some network.
Thanks.

**Comment by ysmood** [comment]
Because `PageAddScriptToEvaluateOnNewDocument` is under the Page domain, so by its name is obviously should work only for a page instance 😂.

From its doc, you can find out that it's designed for navigation and iframes, not a hook for every new page.

Injecting a script to every page should follow the hook design pattern. So what you should do is listen to page creation events and run a script for each page.

I think I won't add an `AddScriptOnEachDoc` helper for you. But I'll an event helper to help you easily hook whatever you want.

**Comment by zjlx** [comment]
OK , Thanks a lot.

**Comment by ysmood** [comment]
`v0.31.0` added some helpers to help you do this. Here's the example:

https://github.com/ysmood/rod/blob/9b680d3afeb2bec4007ccea53ea2b1d70f602976/examples_test.go#L204-L226

**Comment by ysmood** [comment]
@zjlx `v0.31.1` add `browser.EachEvent` helper to make it even easier:

https://github.com/ysmood/rod/blob/f04616495a3a1d755e88b2e335f8063327f75581/examples_test.go#L219-L225

**Comment by khaitranvan96kt** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> I used this code for fake browser fingerprint ,
> 
> ```go
> proto.PageEnable{}.Call(page)
> 
> proto.PageAddScriptToEvaluateOnNewDocument{
> 	Source: fingerprint,
> }.Call(page)
> ```
> 
> the js code from https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth
> I don't known why need `proto.PageEnable` ,but if I don't write it the `proto.PageAddScriptToEvaluateOnNewDocument` not works.
> `proto.PageAddScriptToEvaluateOnNewDocument` only works on current page/tab not working on a link click new pages/tabs.
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> Can you add a function to add JS script for all browser's pages/tabs something like hook browser's page or some network.
> Thanks.

Can you give me the Script to fake the fingerprint?

**Comment by ysmood** [comment]
@khaitranvan96kt You might want to use [bypass](https://github.com/go-rod/bypass) lib to bypass the bot detection:

https://github.com/go-rod/bypass/blob/master/example/main.go

**Comment by khaitranvan96kt** [comment]
> @khaitranvan96kt You might want to use [bypass](https://github.com/go-rod/bypass) lib to bypass the bot detection:
> 
> https://github.com/go-rod/bypass/blob/master/example/main.go

```
func TestRequestFingerprint2(t *testing.T) {
	for i := 0; i < 3; i++ {
		browser := rod.New().Connect()
		page := bypass.Page(browser)
		page.Navigate("https://fingerprintjs.com/demo").WaitLoad()
		time.Sleep(10 * time.Second)
		filename := fmt.Sprintf("browser_%d.png", i)
		page.ScreenshotFullPage(filename)
		browser.Close()
	}
	fmt.Println("All done, check the screenshot. ✨")
}
```

It does not work, it is still detected.

**Comment by ysmood** [comment]
@khaitranvan96kt  Can you raise an issue about https://fingerprintjs.com? It's not bot detection, fingerprinting is another topic.

**Comment by khaitranvan96kt** [comment]
> @khaitranvan96kt Can you raise an issue about https://fingerprintjs.com? It's not bot detection, fingerprinting is another topic.

Yes I know, so I asked @zjlx

**Comment by zjlx** [comment]
> > @khaitranvan96kt Can you raise an issue about https://fingerprintjs.com? It's not bot detection, fingerprinting is another topic.
> 
> Yes I know, so I asked @zjlx

Against browser fingerprints, the above JS plug-in is only a fixed value, and it can't achieve random parameters. If you want more configuration, you need to implement it by yourself, learn about JS related knowledge such as webgl and canvas, and set different parameters to meet the requirements of simulating different browser fingerprints.

**Comment by khaitranvan96kt** [comment]
> > > @khaitranvan96kt Can you raise an issue about https://fingerprintjs.com? It's not bot detection, fingerprinting is another topic.
> > 
> > 
> > Yes I know, so I asked @zjlx
> 
> Against browser fingerprints, the above JS plug-in is only a fixed value, and it can't achieve random parameters. If you want more configuration, you need to implement it by yourself, learn about JS related knowledge such as webgl and canvas, and set different parameters to meet the requirements of simulating different browser fingerprints.

wow, thank you so much for suggesting me
