### ISSUE TITLE
Can we provide a way to create a new stealth window。

### ISSUE THREAD

**Issue by simpleMemory** [ysmood/rod#3]
I want to use an existing browser instance to create a new context,
In puppeteer：
`
browser.createIncognitoBrowserContext()
// Target.createBrowserContext
`

**Comment by ysmood** [comment]
Sure, we can. Just a simple function call: https://chromedevtools.github.io/devtools-protocol/tot/Target#method-createBrowserContext

**Comment by simpleMemory** [comment]
If it can provide more convenient APIs, it should be able to attract more users.

**Comment by ysmood** [comment]
Thanks for your feedback. Added in 9e1ace46d9e5d02d00a1f8a65eda48d873365b81, released in v0.23.1

[Example code](https://github.com/ysmood/rod/blob/9e1ace46d9e5d02d00a1f8a65eda48d873365b81/browser_test.go#L28)

Please close this ticket if you feel the implementation is what you want.
