### ISSUE TITLE
请教一下 FindByURL 这个方法怎么用呢

### ISSUE THREAD

**Issue by lanpan999** [ysmood/rod#37]
请教一下 FindByURL 这个方法怎么用呢，看了文档，新手没搞懂具体咋用，大佬方便时候加个简单实际案例吗，谢谢啦！

**Comment by ysmood** [comment]
单元测试就是最好的例子，每个函数都有测试，你可以直接搜索函数名来找相关测试。

https://github.com/ysmood/rod/blob/469213ccfe13c4f53217c96120c7291c9db83ffb/query_test.go#L19

这个意思是在所有 tab 中找到 url 匹配正则 `click.html` 的页面。这个方法返回一个 Page 对象。

**Comment by lanpan999** [comment]
收到 ，感谢
