### ISSUE TITLE
请教一下怎么获取网页里全部标签呢

### ISSUE THREAD

**Issue by lanpan999** [ysmood/rod#39]
觉得这个项目很好，想做个 url资产收集的爬虫。 想请教下 怎么获取一个网页里全部的<a href></a> 标签呢，目前我只能一次获取一个
el := browser.Page("https://movie.douban.com/top250").Element("a")
fmt.Println(el.Text())

感谢大佬的指导！

**Comment by ysmood** [comment]
```go
list := browser.Page("https://movie.douban.com/top250").WaitLoad().Elements("a")
fmt.Println(list[0].Text())
```

**Comment by lanpan999** [comment]
感谢🙏
