### ISSUE TITLE
Getting error while running the binary

### ISSUE THREAD

**Issue by rahul-satal** [ysmood/rod#4]
I am following the installation steps. While trying to create binary I am getting the below error:- 

standard_init_linux.go:211: exec user process caused "no such file or directory"

![image](https://user-images.githubusercontent.com/6859257/77948697-6d975b80-72e3-11ea-9f2b-5db9e8d16466.png)

Below is the output of Docker version command
![image](https://user-images.githubusercontent.com/6859257/77948895-bb13c880-72e3-11ea-85fd-59a84e69f0e4.png)

I am running it on Ubuntu. I have installed Docker and cloned the repo. Please let me know if I am missing anything.

**Comment by ysmood** [comment]
I think you missed the first line of the doc:

<img width="679" alt="Screen Shot 2020-03-31 at 3 53 13" src="https://user-images.githubusercontent.com/1415488/77950307-42246900-7303-11ea-96bc-eee41cc63af1.png">

Are you sure you understand what the first line does?

**Comment by rahul-satal** [comment]
Thanks @ysmood for the prompt reply.

I ran the file line command as well. It worked fine and the rod.test executable file is also created successfully as shown in the below screenshot.
![image](https://user-images.githubusercontent.com/6859257/77998871-660d9c00-734f-11ea-9959-957e30c4e35c.png)

I have also pulled your last commit and run the below commands
```
# build and run the tests of rod repo
docker build -t test https://github.com/ysmood/rod.git
docker run --rm --cap-add=SYS_ADMIN -it test
```
Here build was created successfully. But, I am getting below errors with docker run command:-

 `[0331/093428.512924:ERROR:gl_implementation.cc(282)] Failed to load /usr/lib/chromium/swiftshader/libGLESv2.so: Error loading shared library /usr/lib/chromium/swiftshader/libGLESv2.so: No such file or directory`

You can see complete logs here - https://play.golang.org/p/5oxGxGK5kL7

I am new to both Golang and docker. So, even if it works I have no idea how can I process further and create my own web testing script. Expecting your help.

**Comment by ysmood** [comment]
The `libGLESv2` is a known issue of Chrome itself which won't affect anything from my view. It's not an bug, just telling you GPU is not available in docker.

**Comment by ysmood** [comment]
Can you tell me why you choose Golang which you are unfamiliar with? How about learning Golang from their official tutorial first?

Then check the [example of Rod](https://pkg.go.dev/github.com/ysmood/rod?tab=doc#example-package-Basic)?

**Comment by ysmood** [comment]
I'm writing a [tutorial](https://github.com/ysmood/github-trending) about using Rod to scrape websites.

Maybe you want to read it when I finished it, maybe you can give me some tips about what you want to learn from the tutorial.

**Comment by rahul-satal** [comment]
> Can you tell me why you choose Golang which you are unfamiliar with? How about learning Golang from their official tutorial first?
> 
> Then read the [examples of Rod](https://github.com/ysmood/rod/blob/master/examples_test.go)?

After learning Golang basics, I am able to use the examples. Thanks

**Comment by ysmood** [comment]
Good to hear that 👍
