### ISSUE TITLE
How to use "PageAddScriptToEvaluateOnNewDocument"?

### ISSUE THREAD

**Issue by pu369** [ysmood/rod#44]
Could you give an example code of "PageAddScriptToEvaluateOnNewDocument"？
I want to change the value of  "window.navigator.webdriver"！

The next line will cause automation to stop
page.Eval(`() => Object.defineProperties(navigator, 'webdriver', {get: () => undefined})`)

**Comment by ysmood** [comment]
```go
proto.PageAddScriptToEvaluateOnNewDocument{
    Source: `console.log("ok")`
}.Call(page)
```

**Comment by ysmood** [comment]
@pu369 your code itself is not valid js, you'd better check the error output and fix your syntax first. The code below works fine for me.

```go
page.Eval(`() => Object.defineProperties(navigator, {
	webdriver: {
		get: () => undefined
	}
})`)
```

**Comment by pu369** [comment]
@ysmood thank you so much.
