### ISSUE TITLE
Does rod support setting http/socks5 proxy?

### ISSUE THREAD

**Issue by NuLL3rr0r** [ysmood/rod#45]
Does rod support setting http/socks5 proxy? If so, with or without authentication?

**Comment by ysmood** [comment]
Yes, rod supports proxy and basic auth. Check this example:

https://github.com/ysmood/rod/blob/5942da20d0dfb4bd8d23ed5480918a0428ffede5/examples_test.go#L155-L175

**Comment by NuLL3rr0r** [comment]
Thank you so much!
