### ISSUE TITLE
How to drag with rod?

### ISSUE THREAD

**Issue by NormalPunch** [ysmood/rod#46]
I tried to solve a drag captcha with rod: 

The captcha will be loaded in an iframe, I can click buttons in the iframe but cannot drag. 

```go
	el:=page.Element(`#iframe`)
	iframe := el.WaitVisible().Frame()

        drag := frame.Element(`#drag`).WaitVisible()

        // copy from the Click 
	box, err := drag.ScrollIntoView().BoxE()
	if err != nil {
		panic(err)
	}

	x := box.Left + box.Width/2
	y := box.Top + box.Height/2

	err = iframe.Mouse.MoveE(x, y, 1)
	if err != nil {
		panic(err)
	}

       iframe.Mouse.Down(proto.InputMouseButtonLeft)
       iframe.Mouse.Move(1, 0)
       iframe.Mouse.Move(1, 0)
       iframe.Mouse.Move(2, 0)
       ...
       iframe.Mouse.Up(proto.InputMouseButtonLeft)

       
```

It seemed that only the `Down` and `Up` success, but the `Move` do nothing with no error. 

Any idea? Thanks!

**Comment by NormalPunch** [comment]
I thought `Swipe` = `Down` - `Moves` - `Up` , but looked into rod a little, really couldn't move, `Down` - `Moves` - `Up` was more like `Click`...

But `Move` worked fine when used alone...I mean, without holding the `InputMouseButtonLeft`

**Comment by NormalPunch** [comment]
OS: Windows 10 x64
Chrome: 83.0.4103.61

**Comment by ysmood** [comment]
Sorry, this is a known issue, I will support it soon:

https://github.com/ysmood/rod/blob/efd99d27e081c6a62603153074a46c3f01759233/page_test.go#L293-L304

**Comment by ysmood** [comment]
But I think you can use this API to achieve it: https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchTouchEvent

Here is the example to use the API above:

https://github.com/ysmood/rod/blob/efd99d27e081c6a62603153074a46c3f01759233/examples_test.go#L177-L217

If I have time I will add a high-level interface to use it more friendly. If you are interested in it, it will be great that if you can help to make a PR for it.

**Comment by ysmood** [comment]
If you look at the puppeteer.js, they have the same issue: https://github.com/puppeteer/puppeteer/issues/4562

**Comment by NormalPunch** [comment]
> I still don't know why it doesn't work. Feels like a bug of Chrome

Shocked at this fact...

**Comment by ysmood** [comment]
But if you use headless mode, it should work as expected. This issue is only for head mode. This test shows the events will happen correctly:

https://github.com/ysmood/rod/blob/f59cc63696ec5beef2bc5ec0541bebd3f50330f1/page_test.go#L293-L315

**Comment by ysmood** [comment]
Rod has the monitor helper which can help you watch what's happening when it runs in the background:

https://github.com/ysmood/rod/blob/f59cc63696ec5beef2bc5ec0541bebd3f50330f1/examples_test.go#L69-L70

**Comment by NormalPunch** [comment]
> But if you use headless mode, it should work as expected. This issue is only for head mode which means you can't watch it on live. This test shows the events will happen correctly:
> 
> https://github.com/ysmood/rod/blob/f59cc63696ec5beef2bc5ec0541bebd3f50330f1/page_test.go#L293-L315
> 
> I think the reason is that in head mode chrome will use the position of your real mouse, not the mocked one. A typical race condition bug which is really hard to resolve (since you still want to interact with the controlled page with the real mouse to debug), that's why this bug is there for so many years.

Thanks @ysmood , but it was still stucked. 😥

Are you using that gitter channel?

**Comment by ysmood** [comment]
Here's the example, it works on headless mode:

```go

func Example() {
	browser := rod.New().Connect()
	defer browser.Close()

	page.Navigate("https://cstaticdun.126.net/api/v2/mobile.v2.9.1.html?captchaId=07e2387ab53a4d6f930b8d9a9be71bdf")

	wait := page.WaitRequestIdle()
	wait()

	box := page.Element(".yidun_slider__icon").Box()
	kit.Dump(box)

	mouse := page.Mouse

	mouse.Move(box.Left, box.Top)
	mouse.Down("left")

	mouse.MoveE(box.Left+100, box.Top, 5) // drag 100px to the right

	page.Screenshot("")

	mouse.Up("left")

	page.Screenshot("")
}
```

**Comment by NormalPunch** [comment]
Ok, I get it now, thanks @ysmood !

**Comment by ysmood** [comment]
The latest chrome has fixed this issue, now it works for both headless and headful.

**Comment by heemike** [comment]
`page.Element("#pager").Box()` ,出现错误，没有这个方法Box()。

**Comment by ysmood** [comment]
The code is outdated, check the new doc:

https://github.com/go-rod/rod/blob/b7f9c86dceff9a429738d0267fd32ef311e41733/input_test.go#L184-L197
