### ISSUE TITLE
stuck in a `chrome://` page

### ISSUE THREAD

**Issue by NormalPunch** [ysmood/rod#52]
```go
// clear everything (cookies/caches/localstorage...) of every domains without restarting the browser. 
	u := launcher.New().
		Set("disable-extensions", "true").
		//Set("start-maximized", "true").
		Set("no-sandbox", "true").
		Set("disable-web-security", "true").
		Delete("enable-automation").
		Headless(false).
		Launch()

	browser := rod.New().ControlURL(u).Connect()
	defer browser.Close()

        page := browser.Pages()[0]

	page.Navigate("chrome://settings/privacy")

	wait := page.WaitRequestIdle()
	wait()

        time.Sleep(time.Second)

        // stuck here
	clearBrowsingData := page.Element("#clearBrowsingData")
	clearBrowsingData.Click()

        time.Sleep(time.Second)

	clearBrowsingDataConfirm := page.Element("#clearBrowsingDataConfirm")
	clearBrowsingDataConfirm.Click()

	// page.Screenshot("")
```

**Comment by ysmood** [comment]
fixed some bugs recently, please try the latest version

**Comment by NormalPunch** [comment]
> fixed some bugs recently, please try the latest version

Yes, always run `go get -u` before building

```
	github.com/ysmood/kit v0.23.0
	github.com/ysmood/rod v0.37.0
```

**Comment by ysmood** [comment]
If you try `document.querySelector("#clearBrowsingData")` it will return null.
When you debug please use `Trace(true)`:

```
rod.New().ControlURL(u).Trace(true).Connect()
```

The reason is this page is using shadow-dom. You have to use something like this:

```go
	clearBrowsingData := page.Element("settings-ui").ShadowRoot().
		Element("#main").ShadowRoot().
		Element("settings-basic-page").ShadowRoot().
		Element("settings-privacy-page").ShadowRoot().
		Element("#clearBrowsingData")
```

**Comment by ysmood** [comment]
😂 Man, you don't have to do this kind of crazy thing, Rod has `browser.Incognito()` to create isolated env.

**Comment by NormalPunch** [comment]
> If you try `document.querySelector("#clearBrowsingData")` it will return null.
> When you debug please use `Trace(true)`:
> 
> ```
> rod.New().ControlURL(u).Trace(true).Connect()
> ```
> 
> It will tell you what rod is doing, this time it's retrying to get something that it can't get.
> 
> <img alt="Screen Shot 2020-06-09 at 22 13 41" width="619" src="https://user-images.githubusercontent.com/1415488/84151611-98015400-aa9e-11ea-81fb-07a60b71824b.png">
> 
> The reason is this page is using shadow-dom. You have to use something like this:
> 
> ```go
> 	clearBrowsingData := page.Element("settings-ui").ShadowRoot().
> 		Element("#main").ShadowRoot().
> 		Element("settings-basic-page").ShadowRoot().
> 		Element("settings-privacy-page").ShadowRoot().
> 		Element("#clearBrowsingData")
> ```
> 
> It's like the iframe, I'm thinking of a way to make it easier but it will take some time.

`Trace` is cool, thx

**Comment by NormalPunch** [comment]
> 😂 Man, you don't have to do this kind of crazy thing, Rod has `browser.Incognito()` to create isolated env.

Yean but too much costs for restarting a browser. And it seems that cdp api cannot clear all domains.

**Comment by ysmood** [comment]
Well if you want to be lazy, use this:

<img width="619" alt="Screen Shot 2020-06-09 at 22 13 41" src="https://user-images.githubusercontent.com/1415488/84154375-fc71e280-aaa1-11ea-9a16-a8e93c819f04.png">

You will get to reduce pain:

```js
document.querySelector("body > settings-ui").shadowRoot.querySelector("#main").shadowRoot.querySelector("settings-basic-page").shadowRoot.querySelector("#basicPage > settings-section:nth-child(7) > settings-privacy-page").shadowRoot.querySelector("#clearBrowsingData").shadowRoot.querySelector("#label")
```

**Comment by ysmood** [comment]
Well if you want to be lazy, use this:

<img width="618" alt="Screen Shot 2020-06-09 at 22 38 27" src="https://user-images.githubusercontent.com/1415488/84154466-1d3a3800-aaa2-11ea-842f-7a7481b6da44.png">

You will get to reduce pain:

```js
document.querySelector("body > settings-ui").shadowRoot.querySelector("#main").shadowRoot.querySelector("settings-basic-page").shadowRoot.querySelector("#basicPage > settings-section:nth-child(7) > settings-privacy-page").shadowRoot.querySelector("#clearBrowsingData").shadowRoot.querySelector("#label")
```

**Comment by NormalPunch** [comment]
Cool, solved, thanks @ysmood
