### ISSUE TITLE
How works Describe() method

### ISSUE THREAD

**Issue by bsbak** [ysmood/rod#55]
Why Describe().Value return empty, but Attributes[value] return real value?
<img width="475" alt="2" src="https://user-images.githubusercontent.com/11431176/84715969-a528b200-af7a-11ea-8d75-57aeab9d951b.png">
<img width="685" alt="1" src="https://user-images.githubusercontent.com/11431176/84715979-a823a280-af7a-11ea-9608-68732ea17476.png">

**Comment by bsbak** [comment]
How can i get a value from <select> tag?

**Comment by bsbak** [comment]
How can i stop waiting for Element? I was use page.Timeout().Element and i got context deadline exceeded error

**Comment by ysmood** [comment]
> How can i stop waiting for Element? I was use page.Timeout().Element and i got context deadline exceeded panic

Have you tried to read the doc?

https://github.com/ysmood/rod/blob/7b44df4c0a59c8a36a54bb68fab57104bda3e24c/examples_test.go#L136-L152

**Comment by ysmood** [comment]
> How can i get a value from `<select>` tag?

Something like this:

```go
page.Element("select").Eval("() => this.value")
```

**Comment by bsbak** [comment]
> > How can i get a value from `<select>` tag?
> 
> Something like this:
> 
> ```go
> page.Element("select").Eval("() => this.value")
> ```

thx for response, but backoff not working...
i was write by your provided example:
<img width="380" alt="1" src="https://user-images.githubusercontent.com/11431176/84770112-ab04ae80-afdf-11ea-871a-5e9a13749911.png">
and result is nothing happens, just see:
<img width="255" alt="2" src="https://user-images.githubusercontent.com/11431176/84770146-b952ca80-afdf-11ea-82b8-4b654b54dbf3.png">
what im doing wrong?

**Comment by bsbak** [comment]
> > How can i stop waiting for Element? I was use page.Timeout().Element and i got context deadline exceeded panic
> 
> Have you tried to read the doc?
> 
> https://github.com/ysmood/rod/blob/7b44df4c0a59c8a36a54bb68fab57104bda3e24c/examples_test.go#L136-L152
> 
> If you use your IDE to jump to the source code of `ElementE`, then jump to the `ElementByJSE`, you will find out if you use nil as the sleeper, no retry will be performed:
> 
> https://github.com/ysmood/rod/blob/7b44df4c0a59c8a36a54bb68fab57104bda3e24c/query.go#L107-L113
> 
> Just two mouse click will take you to the doc.

thx for response, but backoff not working...
i was write by your provided example:
<img width="380" alt="1" src="https://user-images.githubusercontent.com/11431176/84770112-ab04ae80-afdf-11ea-871a-5e9a13749911.png">
and result is nothing happens (i was waiting much more time than 60 sec), just see:
<img width="255" alt="2" src="https://user-images.githubusercontent.com/11431176/84770146-b952ca80-afdf-11ea-82b8-4b654b54dbf3.png">
what im doing wrong?

**Comment by ysmood** [comment]
because your page doesn't have this element, it will retry forever, backoff is just the time to sleep, it will never stop retry. If you want timeout you need to use `page.Timeout(your_timeout).ElementE` to get the timeout err (no panic if you use ElementE, panic if you use Element)

**Comment by ysmood** [comment]
Open your browser inspector console, run js `docuement.querySelector("#gotoCA")`, I think it returns null.

**Comment by ysmood** [comment]
If you read the doc, the 60 sec you set is the max interval, it's not the max time to wait until timeout. It means when the interval grows to 60 sec, it will not grow anymore, each retry will sleep no more than 60 sec.

https://godoc.org/github.com/ysmood/kit/pkg/utils#BackoffSleeper

<img width="732" alt="Screen Shot 2020-06-16 at 21 21 19" src="https://user-images.githubusercontent.com/1415488/84773443-6137ba80-b017-11ea-8238-9e21a6d9a5dc.png">
