### ISSUE TITLE
Cannot get element inside Iframe.

### ISSUE THREAD

**Issue by alufrew** [ysmood/rod#6]
Cannot get element inside iFrame. When last code line is invoked browser just hangs though i see element in it. When printing FrameID and isFrame I get some ID and true values so I assume that iFrame instance was created. How can I debug it to know the reason?

`url := launcher.New().
	Headless(false). 
	Launch()

browser := rod.New().ControlURL(url).Connect()
defer browser.Close()
	
page := browser.Page("test_url")
fr := page.Element("#iframe_selector").Frame()

fmt.Println(fr.FrameID)
fmt.Println(fr.IsIframe())

fmt.Println(fr.Element("#element_selector").Describe().Type)`

**Comment by ysmood** [comment]
Usually, you just use `document.querySelector("#iframe_selector")` directly on the devtools console to debug.
I think you won't be able to find it in the browser either. I see people encounter the similar issues all the time. Such as iframe inside another iframe you need to call `Frame()` for each level. Such as query shadow DOM elements, you have to use special js to handle them, etc.

If you can provide me the page I can help you to figure out the problem. If I can't reproduce your issue I'm afraid that I can't do much about it.

Here the example of nested iframes: https://github.com/ysmood/rod/blob/a072993e8f2e5b768bf92f5a517a7fca21a3e2ce/element_test.go#L36

**Comment by alufrew** [comment]
Hm. document.querySelector("#iframe_selector") find element under iframe context (if you select it in console manually). Can I get current iFrame name when I switched to it?

**Comment by ysmood** [comment]
Can you do something like this for me?

<img width="526" alt="Screen Shot 2020-04-23 at 0 22 48" src="https://user-images.githubusercontent.com/1415488/80000831-9aace780-84f8-11ea-845d-4ff870330aa6.png">

**Comment by ysmood** [comment]
To get the details about the iframe you can just do something like this

```go
fmt.Println(fr.Element("#element_selector").Describe())
```

**Comment by alufrew** [comment]
Hi. It's nothing much really. 

Copy selector just returns: #contact-email.

**Comment by ysmood** [comment]
You sure it's not nested iframes and not shadow dom?

**Comment by alufrew** [comment]
As far as I can see not. Here you can launch test mock code to go to iFrame. I created it for debug purposes so don't mind things like sleep.


package main

import (
   "fmt"
   "time"

   "github.com/ysmood/rod"
   "github.com/ysmood/rod/lib/launcher"

   "gitlab.zeo.lcl/lumis-web-account/external-scenario-tests/client/subscriptionpurchase"
)

var (
   logInEmailField   = subscriptionpurchase.NewIDSelector("login_email")
   logInSubmitButton = subscriptionpurchase.NewIDSelector("login_submit")
   monthlyPlan       = subscriptionpurchase.NewXpathSelector("//p/button[@data-fsc-item-path='test-clario-1mo']")
)

func main() {
   url := launcher.New().
      Headless(false). // run chrome on foreground
      Launch()

   browser := rod.New().ControlURL(url).Connect()
   defer browser.Close()

   page := browser.Page("https://buynow.account.sz.clario.co/lumis_fastspring_bn_emulator_with_login.html")

   page.Element("#login_email").Input("77@yopmail.com")
   page.Element("#login_submit").Click()
   time.Sleep(5 * time.Second)
   page.ElementX("//p/button[@data-fsc-item-path='test-clario-1mo']").Click()

   fr := page.Element("#fsc-popup-frame").Frame()
   time.Sleep(2 * time.Second)

   fmt.Println(fr.IsIframe())

   fr.Element("#contact-last-name").Click()
}

**Comment by ysmood** [comment]
Rod is designed to prevent the use of `time.Sleep`. You can use `WaitInvisible`, `WaitStable` instead, here the example code:

```go
package main

import (
	"github.com/ysmood/kit"
	"github.com/ysmood/rod"
	"github.com/ysmood/rod/lib/launcher"
)

func main() {
	url := launcher.New().
		Headless(false). // run chrome on foreground
		Launch()

	browser := rod.New().ControlURL(url).Connect()
	defer browser.Close()

	page := browser.Page("https://buynow.account.sz.clario.co/lumis_fastspring_bn_emulator_with_login.html")

	page.Element("#login_email").Input("77@yopmail.com")
	page.Element("#login_submit").Click().WaitInvisible()
	page.ElementX("//p/button[@data-fsc-item-path='test-clario-1mo']").Click()

	fr := page.Element("#fsc-popup-frame").Frame()

	fr.Element("#contact-last-name").WaitStable().Click()

	kit.Pause()
}
```

**Comment by ysmood** [comment]
The issue is caused by `site-per-process`, you can use the `rod v0.25.7` to overcome it.

I thought I don't need site-per-process anymore but seems like we still have to keep it, hope in the future chrome can expose a special API for iframe to handle js inject.

**Comment by alufrew** [comment]
Thank you for fix. It's working now. I used time.Sleep just to make sure that framework doen't hang before iFrame is loaded. It wont be used in actual code.

**Comment by ysmood** [comment]
Good to hear that 👍
