### ISSUE TITLE
click event error

### ISSUE THREAD

**Issue by bsbak** [ysmood/rod#60]
Hey, big thx for ur stuff! 
Im trying to click on element, but every time i got error, whats wrong?
<img width="270" alt="2" src="https://user-images.githubusercontent.com/11431176/85411412-00593680-b571-11ea-804a-fdd45560a0de.png">

<img width="488" alt="1" src="https://user-images.githubusercontent.com/11431176/85411353-e881b280-b570-11ea-98d0-09147885c9a9.png">

**Comment by ysmood** [comment]
Looks like a bug, can you share me more information, so that I can reproduce it on my local?

**Comment by ysmood** [comment]
I released `v0.39.0`, if it doesn't fix your issue, please let me know.
