### ISSUE TITLE
lauch browser with socks5 auth

### ISSUE THREAD

**Issue by bsbak** [ysmood/rod#62]
How can i run browser with socks5 auth? I was try (see image), but it not working...
<img width="597" alt="1" src="https://user-images.githubusercontent.com/11431176/85418490-811c3080-b579-11ea-8297-465017c338d8.png">

**Comment by ysmood** [comment]
`proxy-server` flag doesn't support `user:pass` section. Here's the example:

https://github.com/ysmood/rod/blob/5562535dfffc8caa47f164334280836c105c1fc9/examples_test.go#L168-L190

Look at this line:

https://github.com/ysmood/rod/blob/5562535dfffc8caa47f164334280836c105c1fc9/examples_test.go#L183

To set user name and password.

**Comment by bsbak** [comment]
> It's a limitation of Chrome itself, `proxy-server` flag doesn't support `user:pass` section. Here's the example to use it properly:
> 
> https://github.com/ysmood/rod/blob/5562535dfffc8caa47f164334280836c105c1fc9/examples_test.go#L168-L190
> 
> To set the user name and password look at this line:
> 
> https://github.com/ysmood/rod/blob/5562535dfffc8caa47f164334280836c105c1fc9/examples_test.go#L183

thx, but not working...
proxy: XQOWcg:BGsBAP78cr@46.8.106.18:5501
its active:
<img width="624" alt="1" src="https://user-images.githubusercontent.com/11431176/85421980-c04c8080-b57d-11ea-8f6d-6176a3250288.png">
code:
<img width="567" alt="2" src="https://user-images.githubusercontent.com/11431176/85422122-e4a85d00-b57d-11ea-8a83-2dbfd3f10d24.png">

**Comment by ysmood** [comment]
Sorry, my example is for HTTP proxy, not socks5, it seems like Chrome itself only supports socks5 without authentication.

See this ticket: https://bugs.chromium.org/p/chromium/issues/detail?id=256785

The solution will be using a golang lib to add an extra layer of a proxy server to handle the auth locally:

```
chrome -> localhost:1111 -> 46.8.106.18:5501
```

The `localhost:1111` is your local proxy to add auth then send to `46.8.106.18:5501`.

**Comment by ysmood** [comment]
I think it's ok to close it for now. If you have more questions, feel free to leave a comment.
