### ISSUE TITLE
How download file

### ISSUE THREAD

**Issue by bsbak** [ysmood/rod#63]
Cant find any example or issue...
How can i get downloaded file, and how to know that download is finished?
Im clicking on link
<img width="44" alt="1" src="https://user-images.githubusercontent.com/11431176/85524751-1cacb000-b611-11ea-98f1-96306b5ba47c.png">
than download begin
<img width="210" alt="2" src="https://user-images.githubusercontent.com/11431176/85524807-2cc48f80-b611-11ea-9bbd-8b4539c09b79.png">

**Comment by bsbak** [comment]
okey, im trying this and it works...
<img width="353" alt="1" src="https://user-images.githubusercontent.com/11431176/85529032-52539800-b615-11ea-80a1-f4f8c1ce6d27.png">

**Comment by bsbak** [comment]
i was trying 
<img width="353" alt="1" src="https://user-images.githubusercontent.com/11431176/85534605-271f7780-b61a-11ea-8f60-3f5af8f6c015.png">
but i got
<img width="418" alt="2" src="https://user-images.githubusercontent.com/11431176/85534726-3ef6fb80-b61a-11ea-83c2-e38a78ac4256.png">

**Comment by ysmood** [comment]
You shouldn't use goroutine here, the example is here:

https://github.com/ysmood/rod/blob/338c508e8f41298b39bfee4aae04ce5cf7ff7ce5/hijack_test.go#L118-L124

As you can see the example doesn't use goroutine at all.

**Comment by bsbak** [comment]
i was trying do like this but nothing happens its, just waits for something, no click event... (i was update package to latest version
<img width="395" alt="1" src="https://user-images.githubusercontent.com/11431176/85547457-969b6400-b626-11ea-822c-0ee019c665e3.png">
)

**Comment by bsbak** [comment]
How get a downloaded file content-type (like .xml, .pdf) if a donwloaded file content type can be different?

**Comment by ysmood** [comment]
https://github.com/ysmood/rod/blob/842ba077344ad45c2d31ee7e99c3df136abe78cb/hijack_test.go#L28-L62

You can get all the request or response information by using `HijackRequests`, such as `Response.Header("Content-Type")`.
