### ISSUE TITLE
wait for transition complete

### ISSUE THREAD

**Issue by bsbak** [ysmood/rod#64]
How can i wait for animation (trasition) complete (like fade out)?

**Comment by ysmood** [comment]
https://github.com/ysmood/rod/blob/842ba077344ad45c2d31ee7e99c3df136abe78cb/examples_test.go#L96-L116

**Comment by bsbak** [comment]
its stops transition, but must waits..

<img width="581" alt="2" src="https://user-images.githubusercontent.com/11431176/85560088-fd267f00-b632-11ea-8b4f-e0e472e9cedb.png">
default color of button is lightblue, when its clicks on button color chages to black and page freezes, i cant do nothing on page... must to close window and restart...
<img width="209" alt="1" src="https://user-images.githubusercontent.com/11431176/85560354-3d85fd00-b633-11ea-9019-2159a7082b55.png">

**Comment by bsbak** [comment]
and sometime click() do not clicks, why? its misses on target element?

**Comment by ysmood** [comment]
Need more information, if I can't reproduce your issue it's hard to tell. Can you provide minimal code that can reproduce your issue? If it's hard to code, a screen record video will be great.

Please don't use a screenshot if possible, it's hard for me to type your code and try it on my local.

Maybe it's better to use https://www.deepl.com/translator to translate your native language if it's hard for you to use English.

**Comment by ysmood** [comment]
BTW, click problem is not related to this issue title, if you want to ask a lot of unrelated questions, maybe it's better to use the chat room: https://discord.gg/CpevuvY
