### ISSUE TITLE
Launching chrome crashed with STATUS_INVALID_IMAGE_HASH

### ISSUE THREAD

**Issue by ydcool** [ysmood/rod#77]
**Rod Version:** v0.39.1

chrome version:  v83.0.4103.116 /windows x64

## To Reproduce

Check before you submit:

- Is this issue general enough to benefit others?
yes
- Can I provide code to reproduce the issue?
just the basic example code
- Can I reduce the unrelated code to make the example minimal?
yes
- Is the example code standalone?
yes

## Expected behavior

Load expected page.

## Actual result

chrome crashed with STATUS_INVALID_IMAGE_HASH

I have googled this error and was given answer with `chrome.exe --disable-features=RendererCodeIntegrity`, but I am new to rod and not sure how to apply that flag in rod.

**Comment by ysmood** [comment]
Check the `examples_test.go` will make you understand the basics of Rod. Check this one for your question:

https://github.com/ysmood/rod/blob/d6517f762538ac739aa27232110095e7436e708b/examples_test.go#L201-L228

Will look like `.Set("disable-features", "RendererCodeIntegrity")`

**Comment by ysmood** [comment]
If you want to append to default flags, it will look like this:
```go
opts, _ := l.GetFlags("disable-features")
l.Set("disable-features", append(opts, "RendererCodeIntegrity")...)
```

**Comment by ydcool** [comment]
@ysmood oh I read those examples but did not noticed that ... now it's works, thank you so much!
