### ISSUE TITLE
Add method to clear field

### ISSUE THREAD

**Issue by alufrew** [ysmood/rod#9]
May I propose an improvement? Can method to clear field be added?  
Or if there is way to do it now - please tell me.

**Comment by ysmood** [comment]
Yes, we have, like what human does:

```go
el.SelectAllText().Input("")
```

**Comment by alufrew** [comment]
Oh. Didn't think of that. Thank you.

**Comment by lucastheisen** [comment]
@ysmood , I dont think this is the case any longer, or at least it is more complicated.  [The current version of `SelectAllText` returns an error, not an `*rod.Element`](https://github.com/go-rod/rod/blob/393ac0d60b53f3c4a9b2a6504d250cbada55b546/element.go#L241-L254) to chain a call...  Perhaps this is just a documentation issue in that you need to call them separately but the process is still "select everything then set the input"
